oraclenosql:
  image: oracle/nosql:latest
  container_name: "kvlite"
  ports:
    - 5000:5000
    - 5001:5001

jerseyapp:
  build: .
  ports:
    - "8080:8080"
  container_name: "client"
  
  links:
    - oraclenosql
  
  environment:
    - ORANOSQL_DOCKER_HOST=kvlite